version: '3.8'
services:
  app:
    image: Macbeth98/url-shortener
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    env_file:
      - .env.production
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
